-- 1: Update 'total_price' whenever a new order_item is added or removed
-- 2: User must purchase the product before reviewing it
-- 3: ürün stoklarda yoksa alamaz
-- 4: ürün stokları 5'in altına düşünce hata versin (AFTER INSERT ON orders or order_items)
-- 5:
-- 6: