-- 1: order_items tablosunda değişim olunca order toplam fiyatı değişsin
-- 2: kullanıcılar satın almadığı bir ürünü değerlendiremez
-- 3: kullanıcılar stoklarda olmayan ürünü sepete ekleyemez
-- 4: sipariş sonrası ürünlerde stok düşsün
-- 5: ürün stokları 3'ün altına düşünce uyarı versin
-- 6: bir kullanıcı bir ürünü birden fazla kez değerlendiremez
-- 7: username değiştirilemez
-- 8: değerlendirmelerde rating 1-5 arası olmak zorunda. (bu create_tables dosyasında)